
name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        uses: docker/login-action@v1.12.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER}}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: | 
            joaobuzato/rotten-potatoes:latest
            joaobuzato/rotten-potatoes:${{github.run_number}}
            
